use chrono::{DateTime, Utc};

pub struct Platform {
    id: i32,
    slug: String,
    fs_slug: String,
    rom_count: String,
    name: String,
    igdb_slug: String,
    moby_slug: String,
    custom_name: String,
    igdb_id: i64,
    sgdb_id: i64,
    moby_id: i64,
    launchbox_id: i64,
    ss_id: i32,
    ra_id: i32,
    hasheous_id: i64,
    tgdb_id: i64,
    category: String,
    generation: i8,
    family_name: String,
    family_slug: String,
    url: String,
    url_logo: String,
    aspect_ratio: String,
    created_at: DateTime<Utc>,
    updated_at: DateTime<Utc>,
    fs_size_bytes: i64,
    is_unidentified: bool,
    is_identified: bool,
    missing_from_fs: bool,
    display_name: String,
}
