use serde::{Deserialize, Serialize};
use tauri::AppHandle;
use tauri_plugin_shell::ShellExt;

use crate::{enums::error::Error, services::downloader::Downloader};

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum RetroarchCore {
    ThreeDengine,
    EightOne,
    TwoZeroFourEight,
    A5200,
    Anarch,
    Ardens,
    Arduous,
    Atari800,
    B2,
    Bk,
    Blastem,
    Bluemsx,
    Boom3,
    Boom3Xp,
    BsnesHdBeta,
    Bsnes,
    Cannonball,
    Cap32,
    Cdi2015,
    Chailove,
    Citra,
    Clownmdemu,
    Craft,
    Crocods,
    Desmume2015,
    Desmume,
    Dice,
    Dinothawr,
    Dirksimple,
    Dolphin,
    DosboxCore,
    DosboxPure,
    DosboxSvn,
    Doublecherrygb,
    DoukutsuRs,
    Easyrpg,
    Ecwolf,
    Ep128emuCore,
    Fbalpha2012Cps1,
    Fbalpha2012Cps2,
    Fbalpha2012Cps3,
    Fbalpha2012,
    Fbalpha2012Neogeo,
    Fbalpha,
    Fbneo,
    Fceumm,
    Fixgb,
    Fixnes,
    Flycast,
    Fmsx,
    Freechaf,
    Freeintv,
    Frodo,
    Fuse,
    Galaksija,
    Gam4980,
    Gambatte,
    Gearboy,
    Gearcoleco,
    Geargrafx,
    Gearsystem,
    GenesisPlusGx,
    GenesisPlusGxWide,
    Geolith,
    Gme,
    Gong,
    Gw,
    Handy,
    Hatari,
    Holani,
    Jaxe,
    Jumpnbump,
    Kronos,
    Lowresnx,
    Lutro,
    M2000,
    Mame2000,
    Mame2003,
    Mame2003Midway,
    Mame2003Plus,
    Mame2010,
    Mame,
    Mcsoftserve,
    MednafenGba,
    MednafenLynx,
    MednafenNgp,
    MednafenPceFast,
    MednafenPce,
    MednafenPcfx,
    MednafenPsxHw,
    MednafenSaturn,
    MednafenSupafaust,
    MednafenSupergrafx,
    MednafenVb,
    MednafenWswan,
    Melonds,
    Melondsds,
    MesenS,
    Mesen,
    Meteor,
    Mgba,
    Minivmac,
    Mojozork,
    MrBoom,
    Mu,
    Mupen64plusNext,
    Nekop2,
    Neocd,
    Nestopia,
    Np2kai,
    Numero,
    Nxengine,
    O2em,
    Oberon,
    Openlara,
    Opera,
    Panda3ds,
    ParallelN64,
    Pcsx2,
    PcsxRearmed,
    Picodrive,
    Play,
    Pocketcdg,
    Pokemini,
    Potator,
    Ppsspp,
    PrBoom,
    Prosystem,
    Puae2021,
    Puae,
    Px68k,
    Qemu,
    Quasi88,
    Quicknes,
    Race,
    Reminiscence,
    Retro8,
    Romcleaner,
    SameCdi,
    Sameboy,
    Sameduck,
    Scummvm,
    Smsplus,
    Snes9x,
    Squirreljme,
    Stella2014,
    Stella2023,
    Stella,
    Superbroswar,
    Swanstation,
    Tamalibretro,
    Tgbdual,
    Theodore,
    Thepowdertoy,
    Tic80,
    Tyrquake,
    Uw8,
    Uzem,
    Vaporspec,
    VbaNext,
    Vbam,
    Vecx,
    Vemulator,
    ViceX64,
    ViceX64sc,
    ViceX128,
    ViceXcbm2,
    ViceXcbm5x0,
    ViceXpet,
    ViceXplus4,
    ViceXscpu64,
    ViceXvic,
    Vircon32,
    Virtualjaguar,
    Virtualxt,
    Vitaquake2Rogue,
    Vitaquake2Xatrix,
    Vitaquake2Zaero,
    Vitaquake2,
    Vitaquake3,
    Wasm4,
    X1,
    Xrick,
    Yabasanshiro,
    Yabause,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum RetroarchRunner {
    FlatpakLinux,
    NativeLinux,
    NativeWindows,
    NativeMacOs,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all(serialize = "camelCase"))]
pub struct RetroarchPlayerConfig {
    config_path: &'static str,
    cores_path: &'static str,
    core_filename: &'static str,
    state_path: &'static str,
    save_path: &'static str,
    rom_path: String,
}

impl RetroarchPlayerConfig {
    pub fn new(config: RetroarchRunner, core: RetroarchCore, rom_path: String) -> Self {
        match config {
            RetroarchRunner::FlatpakLinux => RetroarchPlayerConfig {
                config_path: "$HOME/.var/app/org.libretro.RetroArch/config/retroarch",
                cores_path: "/cores",
                state_path: "/states",
                save_path: "/saves",
                rom_path,
                core_filename: match core {
                    RetroarchCore::ThreeDengine => "3dengine_libretro.so",
                    RetroarchCore::EightOne => "81_libretro.so",
                    RetroarchCore::TwoZeroFourEight => "2048_libretro.so",
                    RetroarchCore::A5200 => "a5200_libretro.so",
                    RetroarchCore::Anarch => "anarch_libretro.so",
                    RetroarchCore::Ardens => "ardens_libretro.so",
                    RetroarchCore::Arduous => "arduous_libretro.so",
                    RetroarchCore::Atari800 => "atari800_libretro.so",
                    RetroarchCore::B2 => "b2_libretro.so",
                    RetroarchCore::Bk => "bk_libretro.so",
                    RetroarchCore::Blastem => "blastem_libretro.so",
                    RetroarchCore::Bluemsx => "bluemsx_libretro.so",
                    RetroarchCore::Boom3 => "boom3_libretro.so",
                    RetroarchCore::Boom3Xp => "boom3_xp_libretro.so",
                    RetroarchCore::BsnesHdBeta => "bsnes_hd_beta_libretro.so",
                    RetroarchCore::Bsnes => "bsnes_libretro.so",
                    RetroarchCore::Cannonball => "cannonball_libretro.so",
                    RetroarchCore::Cap32 => "cap32_libretro.so",
                    RetroarchCore::Cdi2015 => "cdi2015_libretro.so",
                    RetroarchCore::Chailove => "chailove_libretro.so",
                    RetroarchCore::Citra => "citra_libretro.so",
                    RetroarchCore::Clownmdemu => "clownmdemu_libretro.so",
                    RetroarchCore::Craft => "craft_libretro.so",
                    RetroarchCore::Crocods => "crocods_libretro.so",
                    RetroarchCore::Desmume2015 => "desmume2015_libretro.so",
                    RetroarchCore::Desmume => "desmume_libretro.so",
                    RetroarchCore::Dice => "dice_libretro.so",
                    RetroarchCore::Dinothawr => "dinothawr_libretro.so",
                    RetroarchCore::Dirksimple => "dirksimple_libretro.so",
                    RetroarchCore::Dolphin => "dolphin_libretro.so",
                    RetroarchCore::DosboxCore => "dosbox_core_libretro.so",
                    RetroarchCore::DosboxPure => "dosbox_pure_libretro.so",
                    RetroarchCore::DosboxSvn => "dosbox_svn_libretro.so",
                    RetroarchCore::Doublecherrygb => "DoubleCherryGB_libretro.so",
                    RetroarchCore::DoukutsuRs => "doukutsu_rs_libretro.so",
                    RetroarchCore::Easyrpg => "easyrpg_libretro.so",
                    RetroarchCore::Ecwolf => "ecwolf_libretro.so",
                    RetroarchCore::Ep128emuCore => "ep128emu_core_libretro.so",
                    RetroarchCore::Fbalpha2012Cps1 => "fbalpha2012_cps1_libretro.so",
                    RetroarchCore::Fbalpha2012Cps2 => "fbalpha2012_cps2_libretro.so",
                    RetroarchCore::Fbalpha2012Cps3 => "fbalpha2012_cps3_libretro.so",
                    RetroarchCore::Fbalpha2012 => "fbalpha2012_libretro.so",
                    RetroarchCore::Fbalpha2012Neogeo => "fbalpha2012_neogeo_libretro.so",
                    RetroarchCore::Fbalpha => "fbalpha_libretro.so",
                    RetroarchCore::Fbneo => "fbneo_libretro.so",
                    RetroarchCore::Fceumm => "fceumm_libretro.so",
                    RetroarchCore::Fixgb => "fixgb_libretro.so",
                    RetroarchCore::Fixnes => "fixnes_libretro.so",
                    RetroarchCore::Flycast => "flycast_libretro.so",
                    RetroarchCore::Fmsx => "fmsx_libretro.so",
                    RetroarchCore::Freechaf => "freechaf_libretro.so",
                    RetroarchCore::Freeintv => "freeintv_libretro.so",
                    RetroarchCore::Frodo => "frodo_libretro.so",
                    RetroarchCore::Fuse => "fuse_libretro.so",
                    RetroarchCore::Galaksija => "galaksija_libretro.so",
                    RetroarchCore::Gam4980 => "gam4980_libretro.so",
                    RetroarchCore::Gambatte => "gambatte_libretro.so",
                    RetroarchCore::Gearboy => "gearboy_libretro.so",
                    RetroarchCore::Gearcoleco => "gearcoleco_libretro.so",
                    RetroarchCore::Geargrafx => "geargrafx_libretro.so",
                    RetroarchCore::Gearsystem => "gearsystem_libretro.so",
                    RetroarchCore::GenesisPlusGx => "genesis_plus_gx_libretro.so",
                    RetroarchCore::GenesisPlusGxWide => "genesis_plus_gx_wide_libretro.so",
                    RetroarchCore::Geolith => "geolith_libretro.so",
                    RetroarchCore::Gme => "gme_libretro.so",
                    RetroarchCore::Gong => "gong_libretro.so",
                    RetroarchCore::Gw => "gw_libretro.so",
                    RetroarchCore::Handy => "handy_libretro.so",
                    RetroarchCore::Hatari => "hatari_libretro.so",
                    RetroarchCore::Holani => "holani_libretro.so",
                    RetroarchCore::Jaxe => "jaxe_libretro.so",
                    RetroarchCore::Jumpnbump => "jumpnbump_libretro.so",
                    RetroarchCore::Kronos => "kronos_libretro.so",
                    RetroarchCore::Lowresnx => "lowresnx_libretro.so",
                    RetroarchCore::Lutro => "lutro_libretro.so",
                    RetroarchCore::M2000 => "m2000_libretro.so",
                    RetroarchCore::Mame2000 => "mame2000_libretro.so",
                    RetroarchCore::Mame2003 => "mame2003_libretro.so",
                    RetroarchCore::Mame2003Midway => "mame2003_midway_libretro.so",
                    RetroarchCore::Mame2003Plus => "mame2003_plus_libretro.so",
                    RetroarchCore::Mame2010 => "mame2010_libretro.so",
                    RetroarchCore::Mame => "mame_libretro.so",
                    RetroarchCore::Mcsoftserve => "mcsoftserve_libretro.so",
                    RetroarchCore::MednafenGba => "mednafen_gba_libretro.so",
                    RetroarchCore::MednafenLynx => "mednafen_lynx_libretro.so",
                    RetroarchCore::MednafenNgp => "mednafen_ngp_libretro.so",
                    RetroarchCore::MednafenPceFast => "mednafen_pce_fast_libretro.so",
                    RetroarchCore::MednafenPce => "mednafen_pce_libretro.so",
                    RetroarchCore::MednafenPcfx => "mednafen_pcfx_libretro.so",
                    RetroarchCore::MednafenPsxHw => "mednafen_psx_hw_libretro.so",
                    RetroarchCore::MednafenSaturn => "mednafen_saturn_libretro.so",
                    RetroarchCore::MednafenSupafaust => "mednafen_supafaust_libretro.so",
                    RetroarchCore::MednafenSupergrafx => "mednafen_supergrafx_libretro.so",
                    RetroarchCore::MednafenVb => "mednafen_vb_libretro.so",
                    RetroarchCore::MednafenWswan => "mednafen_wswan_libretro.so",
                    RetroarchCore::Melonds => "melonds_libretro.so",
                    RetroarchCore::Melondsds => "melondsds_libretro.so",
                    RetroarchCore::MesenS => "mesen-s_libretro.so",
                    RetroarchCore::Mesen => "mesen_libretro.so",
                    RetroarchCore::Meteor => "meteor_libretro.so",
                    RetroarchCore::Mgba => "mgba_libretro.so",
                    RetroarchCore::Minivmac => "minivmac_libretro.so",
                    RetroarchCore::Mojozork => "mojozork_libretro.so",
                    RetroarchCore::MrBoom => "mr_boom_libretro.so",
                    RetroarchCore::Mu => "mu_libretro.so",
                    RetroarchCore::Mupen64plusNext => "mupen64plus_next_libretro.so",
                    RetroarchCore::Nekop2 => "nekop2_libretro.so",
                    RetroarchCore::Neocd => "neocd_libretro.so",
                    RetroarchCore::Nestopia => "nestopia_libretro.so",
                    RetroarchCore::Np2kai => "np2kai_libretro.so",
                    RetroarchCore::Numero => "numero_libretro.so",
                    RetroarchCore::Nxengine => "nxengine_libretro.so",
                    RetroarchCore::O2em => "o2em_libretro.so",
                    RetroarchCore::Oberon => "oberon_libretro.so",
                    RetroarchCore::Openlara => "openlara_libretro.so",
                    RetroarchCore::Opera => "opera_libretro.so",
                    RetroarchCore::Panda3ds => "panda3ds_libretro.so",
                    RetroarchCore::ParallelN64 => "parallel_n64_libretro.so",
                    RetroarchCore::Pcsx2 => "pcsx2_libretro.so",
                    RetroarchCore::PcsxRearmed => "pcsx_rearmed_libretro.so",
                    RetroarchCore::Picodrive => "picodrive_libretro.so",
                    RetroarchCore::Play => "play_libretro.so",
                    RetroarchCore::Pocketcdg => "pocketcdg_libretro.so",
                    RetroarchCore::Pokemini => "pokemini_libretro.so",
                    RetroarchCore::Potator => "potator_libretro.so",
                    RetroarchCore::Ppsspp => "ppsspp_libretro.so",
                    RetroarchCore::PrBoom => "prboom_libretro.so",
                    RetroarchCore::Prosystem => "prosystem_libretro.so",
                    RetroarchCore::Puae2021 => "puae2021_libretro.so",
                    RetroarchCore::Puae => "puae_libretro.so",
                    RetroarchCore::Px68k => "px68k_libretro.so",
                    RetroarchCore::Qemu => "qemu_libretro.so",
                    RetroarchCore::Quasi88 => "quasi88_libretro.so",
                    RetroarchCore::Quicknes => "quicknes_libretro.so",
                    RetroarchCore::Race => "race_libretro.so",
                    RetroarchCore::Reminiscence => "reminiscence_libretro.so",
                    RetroarchCore::Retro8 => "retro8_libretro.so",
                    RetroarchCore::Romcleaner => "romcleaner_libretro.so",
                    RetroarchCore::SameCdi => "same_cdi_libretro.so",
                    RetroarchCore::Sameboy => "sameboy_libretro.so",
                    RetroarchCore::Sameduck => "sameduck_libretro.so",
                    RetroarchCore::Scummvm => "scummvm_libretro.so",
                    RetroarchCore::Smsplus => "smsplus_libretro.so",
                    RetroarchCore::Snes9x => "snes9x_libretro.so",
                    RetroarchCore::Squirreljme => "squirreljme_libretro.so",
                    RetroarchCore::Stella2014 => "stella2014_libretro.so",
                    RetroarchCore::Stella2023 => "stella2023_libretro.so",
                    RetroarchCore::Stella => "stella_libretro.so",
                    RetroarchCore::Superbroswar => "superbroswar_libretro.so",
                    RetroarchCore::Swanstation => "swanstation_libretro.so",
                    RetroarchCore::Tamalibretro => "tamalibretro_libretro.so",
                    RetroarchCore::Tgbdual => "tgbdual_libretro.so",
                    RetroarchCore::Theodore => "theodore_libretro.so",
                    RetroarchCore::Thepowdertoy => "thepowdertoy_libretro.so",
                    RetroarchCore::Tic80 => "tic80_libretro.so",
                    RetroarchCore::Tyrquake => "tyrquake_libretro.so",
                    RetroarchCore::Uw8 => "uw8_libretro.so",
                    RetroarchCore::Uzem => "uzem_libretro.so",
                    RetroarchCore::Vaporspec => "vaporspec_libretro.so",
                    RetroarchCore::VbaNext => "vba_next_libretro.so",
                    RetroarchCore::Vbam => "vbam_libretro.so",
                    RetroarchCore::Vecx => "vecx_libretro.so",
                    RetroarchCore::Vemulator => "vemulator_libretro.so",
                    RetroarchCore::ViceX64 => "vice_x64_libretro.so",
                    RetroarchCore::ViceX64sc => "vice_x64sc_libretro.so",
                    RetroarchCore::ViceX128 => "vice_x128_libretro.so",
                    RetroarchCore::ViceXcbm2 => "vice_xcbm2_libretro.so",
                    RetroarchCore::ViceXcbm5x0 => "vice_xcbm5x0_libretro.so",
                    RetroarchCore::ViceXpet => "vice_xpet_libretro.so",
                    RetroarchCore::ViceXplus4 => "vice_xplus4_libretro.so",
                    RetroarchCore::ViceXscpu64 => "vice_xscpu64_libretro.so",
                    RetroarchCore::ViceXvic => "vice_xvic_libretro.so",
                    RetroarchCore::Vircon32 => "vircon32_libretro.so",
                    RetroarchCore::Virtualjaguar => "virtualjaguar_libretro.so",
                    RetroarchCore::Virtualxt => "virtualxt_libretro.so",
                    RetroarchCore::Vitaquake2Rogue => "vitaquake2-rogue_libretro.so",
                    RetroarchCore::Vitaquake2Xatrix => "vitaquake2-xatrix_libretro.so",
                    RetroarchCore::Vitaquake2Zaero => "vitaquake2-zaero_libretro.so",
                    RetroarchCore::Vitaquake2 => "vitaquake2_libretro.so",
                    RetroarchCore::Vitaquake3 => "vitaquake3_libretro.so",
                    RetroarchCore::Wasm4 => "wasm4_libretro.so",
                    RetroarchCore::X1 => "x1_libretro.so",
                    RetroarchCore::Xrick => "xrick_libretro.so",
                    RetroarchCore::Yabasanshiro => "yabasanshiro_libretro.so",
                    RetroarchCore::Yabause => "yabause_libretro.so",
                },
            },
            RetroarchRunner::NativeLinux => RetroarchPlayerConfig {
                config_path: "$HOME/.config/retroarch",
                cores_path: "/cores",
                state_path: "/states",
                save_path: "/saves",
                rom_path,
                core_filename: match core {
                    RetroarchCore::ThreeDengine => "3dengine_libretro.so",
                    RetroarchCore::EightOne => "81_libretro.so",
                    RetroarchCore::TwoZeroFourEight => "2048_libretro.so",
                    RetroarchCore::A5200 => "a5200_libretro.so",
                    RetroarchCore::Anarch => "anarch_libretro.so",
                    RetroarchCore::Ardens => "ardens_libretro.so",
                    RetroarchCore::Arduous => "arduous_libretro.so",
                    RetroarchCore::Atari800 => "atari800_libretro.so",
                    RetroarchCore::B2 => "b2_libretro.so",
                    RetroarchCore::Bk => "bk_libretro.so",
                    RetroarchCore::Blastem => "blastem_libretro.so",
                    RetroarchCore::Bluemsx => "bluemsx_libretro.so",
                    RetroarchCore::Boom3 => "boom3_libretro.so",
                    RetroarchCore::Boom3Xp => "boom3_xp_libretro.so",
                    RetroarchCore::BsnesHdBeta => "bsnes_hd_beta_libretro.so",
                    RetroarchCore::Bsnes => "bsnes_libretro.so",
                    RetroarchCore::Cannonball => "cannonball_libretro.so",
                    RetroarchCore::Cap32 => "cap32_libretro.so",
                    RetroarchCore::Cdi2015 => "cdi2015_libretro.so",
                    RetroarchCore::Chailove => "chailove_libretro.so",
                    RetroarchCore::Citra => "citra_libretro.so",
                    RetroarchCore::Clownmdemu => "clownmdemu_libretro.so",
                    RetroarchCore::Craft => "craft_libretro.so",
                    RetroarchCore::Crocods => "crocods_libretro.so",
                    RetroarchCore::Desmume2015 => "desmume2015_libretro.so",
                    RetroarchCore::Desmume => "desmume_libretro.so",
                    RetroarchCore::Dice => "dice_libretro.so",
                    RetroarchCore::Dinothawr => "dinothawr_libretro.so",
                    RetroarchCore::Dirksimple => "dirksimple_libretro.so",
                    RetroarchCore::Dolphin => "dolphin_libretro.so",
                    RetroarchCore::DosboxCore => "dosbox_core_libretro.so",
                    RetroarchCore::DosboxPure => "dosbox_pure_libretro.so",
                    RetroarchCore::DosboxSvn => "dosbox_svn_libretro.so",
                    RetroarchCore::Doublecherrygb => "DoubleCherryGB_libretro.so",
                    RetroarchCore::DoukutsuRs => "doukutsu_rs_libretro.so",
                    RetroarchCore::Easyrpg => "easyrpg_libretro.so",
                    RetroarchCore::Ecwolf => "ecwolf_libretro.so",
                    RetroarchCore::Ep128emuCore => "ep128emu_core_libretro.so",
                    RetroarchCore::Fbalpha2012Cps1 => "fbalpha2012_cps1_libretro.so",
                    RetroarchCore::Fbalpha2012Cps2 => "fbalpha2012_cps2_libretro.so",
                    RetroarchCore::Fbalpha2012Cps3 => "fbalpha2012_cps3_libretro.so",
                    RetroarchCore::Fbalpha2012 => "fbalpha2012_libretro.so",
                    RetroarchCore::Fbalpha2012Neogeo => "fbalpha2012_neogeo_libretro.so",
                    RetroarchCore::Fbalpha => "fbalpha_libretro.so",
                    RetroarchCore::Fbneo => "fbneo_libretro.so",
                    RetroarchCore::Fceumm => "fceumm_libretro.so",
                    RetroarchCore::Fixgb => "fixgb_libretro.so",
                    RetroarchCore::Fixnes => "fixnes_libretro.so",
                    RetroarchCore::Flycast => "flycast_libretro.so",
                    RetroarchCore::Fmsx => "fmsx_libretro.so",
                    RetroarchCore::Freechaf => "freechaf_libretro.so",
                    RetroarchCore::Freeintv => "freeintv_libretro.so",
                    RetroarchCore::Frodo => "frodo_libretro.so",
                    RetroarchCore::Fuse => "fuse_libretro.so",
                    RetroarchCore::Galaksija => "galaksija_libretro.so",
                    RetroarchCore::Gam4980 => "gam4980_libretro.so",
                    RetroarchCore::Gambatte => "gambatte_libretro.so",
                    RetroarchCore::Gearboy => "gearboy_libretro.so",
                    RetroarchCore::Gearcoleco => "gearcoleco_libretro.so",
                    RetroarchCore::Geargrafx => "geargrafx_libretro.so",
                    RetroarchCore::Gearsystem => "gearsystem_libretro.so",
                    RetroarchCore::GenesisPlusGx => "genesis_plus_gx_libretro.so",
                    RetroarchCore::GenesisPlusGxWide => "genesis_plus_gx_wide_libretro.so",
                    RetroarchCore::Geolith => "geolith_libretro.so",
                    RetroarchCore::Gme => "gme_libretro.so",
                    RetroarchCore::Gong => "gong_libretro.so",
                    RetroarchCore::Gw => "gw_libretro.so",
                    RetroarchCore::Handy => "handy_libretro.so",
                    RetroarchCore::Hatari => "hatari_libretro.so",
                    RetroarchCore::Holani => "holani_libretro.so",
                    RetroarchCore::Jaxe => "jaxe_libretro.so",
                    RetroarchCore::Jumpnbump => "jumpnbump_libretro.so",
                    RetroarchCore::Kronos => "kronos_libretro.so",
                    RetroarchCore::Lowresnx => "lowresnx_libretro.so",
                    RetroarchCore::Lutro => "lutro_libretro.so",
                    RetroarchCore::M2000 => "m2000_libretro.so",
                    RetroarchCore::Mame2000 => "mame2000_libretro.so",
                    RetroarchCore::Mame2003 => "mame2003_libretro.so",
                    RetroarchCore::Mame2003Midway => "mame2003_midway_libretro.so",
                    RetroarchCore::Mame2003Plus => "mame2003_plus_libretro.so",
                    RetroarchCore::Mame2010 => "mame2010_libretro.so",
                    RetroarchCore::Mame => "mame_libretro.so",
                    RetroarchCore::Mcsoftserve => "mcsoftserve_libretro.so",
                    RetroarchCore::MednafenGba => "mednafen_gba_libretro.so",
                    RetroarchCore::MednafenLynx => "mednafen_lynx_libretro.so",
                    RetroarchCore::MednafenNgp => "mednafen_ngp_libretro.so",
                    RetroarchCore::MednafenPceFast => "mednafen_pce_fast_libretro.so",
                    RetroarchCore::MednafenPce => "mednafen_pce_libretro.so",
                    RetroarchCore::MednafenPcfx => "mednafen_pcfx_libretro.so",
                    RetroarchCore::MednafenPsxHw => "mednafen_psx_hw_libretro.so",
                    RetroarchCore::MednafenSaturn => "mednafen_saturn_libretro.so",
                    RetroarchCore::MednafenSupafaust => "mednafen_supafaust_libretro.so",
                    RetroarchCore::MednafenSupergrafx => "mednafen_supergrafx_libretro.so",
                    RetroarchCore::MednafenVb => "mednafen_vb_libretro.so",
                    RetroarchCore::MednafenWswan => "mednafen_wswan_libretro.so",
                    RetroarchCore::Melonds => "melonds_libretro.so",
                    RetroarchCore::Melondsds => "melondsds_libretro.so",
                    RetroarchCore::MesenS => "mesen-s_libretro.so",
                    RetroarchCore::Mesen => "mesen_libretro.so",
                    RetroarchCore::Meteor => "meteor_libretro.so",
                    RetroarchCore::Mgba => "mgba_libretro.so",
                    RetroarchCore::Minivmac => "minivmac_libretro.so",
                    RetroarchCore::Mojozork => "mojozork_libretro.so",
                    RetroarchCore::MrBoom => "mr_boom_libretro.so",
                    RetroarchCore::Mu => "mu_libretro.so",
                    RetroarchCore::Mupen64plusNext => "mupen64plus_next_libretro.so",
                    RetroarchCore::Nekop2 => "nekop2_libretro.so",
                    RetroarchCore::Neocd => "neocd_libretro.so",
                    RetroarchCore::Nestopia => "nestopia_libretro.so",
                    RetroarchCore::Np2kai => "np2kai_libretro.so",
                    RetroarchCore::Numero => "numero_libretro.so",
                    RetroarchCore::Nxengine => "nxengine_libretro.so",
                    RetroarchCore::O2em => "o2em_libretro.so",
                    RetroarchCore::Oberon => "oberon_libretro.so",
                    RetroarchCore::Openlara => "openlara_libretro.so",
                    RetroarchCore::Opera => "opera_libretro.so",
                    RetroarchCore::Panda3ds => "panda3ds_libretro.so",
                    RetroarchCore::ParallelN64 => "parallel_n64_libretro.so",
                    RetroarchCore::Pcsx2 => "pcsx2_libretro.so",
                    RetroarchCore::PcsxRearmed => "pcsx_rearmed_libretro.so",
                    RetroarchCore::Picodrive => "picodrive_libretro.so",
                    RetroarchCore::Play => "play_libretro.so",
                    RetroarchCore::Pocketcdg => "pocketcdg_libretro.so",
                    RetroarchCore::Pokemini => "pokemini_libretro.so",
                    RetroarchCore::Potator => "potator_libretro.so",
                    RetroarchCore::Ppsspp => "ppsspp_libretro.so",
                    RetroarchCore::PrBoom => "prboom_libretro.so",
                    RetroarchCore::Prosystem => "prosystem_libretro.so",
                    RetroarchCore::Puae2021 => "puae2021_libretro.so",
                    RetroarchCore::Puae => "puae_libretro.so",
                    RetroarchCore::Px68k => "px68k_libretro.so",
                    RetroarchCore::Qemu => "qemu_libretro.so",
                    RetroarchCore::Quasi88 => "quasi88_libretro.so",
                    RetroarchCore::Quicknes => "quicknes_libretro.so",
                    RetroarchCore::Race => "race_libretro.so",
                    RetroarchCore::Reminiscence => "reminiscence_libretro.so",
                    RetroarchCore::Retro8 => "retro8_libretro.so",
                    RetroarchCore::Romcleaner => "romcleaner_libretro.so",
                    RetroarchCore::SameCdi => "same_cdi_libretro.so",
                    RetroarchCore::Sameboy => "sameboy_libretro.so",
                    RetroarchCore::Sameduck => "sameduck_libretro.so",
                    RetroarchCore::Scummvm => "scummvm_libretro.so",
                    RetroarchCore::Smsplus => "smsplus_libretro.so",
                    RetroarchCore::Snes9x => "snes9x_libretro.so",
                    RetroarchCore::Squirreljme => "squirreljme_libretro.so",
                    RetroarchCore::Stella2014 => "stella2014_libretro.so",
                    RetroarchCore::Stella2023 => "stella2023_libretro.so",
                    RetroarchCore::Stella => "stella_libretro.so",
                    RetroarchCore::Superbroswar => "superbroswar_libretro.so",
                    RetroarchCore::Swanstation => "swanstation_libretro.so",
                    RetroarchCore::Tamalibretro => "tamalibretro_libretro.so",
                    RetroarchCore::Tgbdual => "tgbdual_libretro.so",
                    RetroarchCore::Theodore => "theodore_libretro.so",
                    RetroarchCore::Thepowdertoy => "thepowdertoy_libretro.so",
                    RetroarchCore::Tic80 => "tic80_libretro.so",
                    RetroarchCore::Tyrquake => "tyrquake_libretro.so",
                    RetroarchCore::Uw8 => "uw8_libretro.so",
                    RetroarchCore::Uzem => "uzem_libretro.so",
                    RetroarchCore::Vaporspec => "vaporspec_libretro.so",
                    RetroarchCore::VbaNext => "vba_next_libretro.so",
                    RetroarchCore::Vbam => "vbam_libretro.so",
                    RetroarchCore::Vecx => "vecx_libretro.so",
                    RetroarchCore::Vemulator => "vemulator_libretro.so",
                    RetroarchCore::ViceX64 => "vice_x64_libretro.so",
                    RetroarchCore::ViceX64sc => "vice_x64sc_libretro.so",
                    RetroarchCore::ViceX128 => "vice_x128_libretro.so",
                    RetroarchCore::ViceXcbm2 => "vice_xcbm2_libretro.so",
                    RetroarchCore::ViceXcbm5x0 => "vice_xcbm5x0_libretro.so",
                    RetroarchCore::ViceXpet => "vice_xpet_libretro.so",
                    RetroarchCore::ViceXplus4 => "vice_xplus4_libretro.so",
                    RetroarchCore::ViceXscpu64 => "vice_xscpu64_libretro.so",
                    RetroarchCore::ViceXvic => "vice_xvic_libretro.so",
                    RetroarchCore::Vircon32 => "vircon32_libretro.so",
                    RetroarchCore::Virtualjaguar => "virtualjaguar_libretro.so",
                    RetroarchCore::Virtualxt => "virtualxt_libretro.so",
                    RetroarchCore::Vitaquake2Rogue => "vitaquake2-rogue_libretro.so",
                    RetroarchCore::Vitaquake2Xatrix => "vitaquake2-xatrix_libretro.so",
                    RetroarchCore::Vitaquake2Zaero => "vitaquake2-zaero_libretro.so",
                    RetroarchCore::Vitaquake2 => "vitaquake2_libretro.so",
                    RetroarchCore::Vitaquake3 => "vitaquake3_libretro.so",
                    RetroarchCore::Wasm4 => "wasm4_libretro.so",
                    RetroarchCore::X1 => "x1_libretro.so",
                    RetroarchCore::Xrick => "xrick_libretro.so",
                    RetroarchCore::Yabasanshiro => "yabasanshiro_libretro.so",
                    RetroarchCore::Yabause => "yabause_libretro.so",
                },
            },
            RetroarchRunner::NativeWindows => RetroarchPlayerConfig {
                config_path: "%APPDATA%\\RetroArch",
                cores_path: "\\cores",
                state_path: "\\states",
                save_path: "\\saves",
                rom_path,
                core_filename: match core {
                    RetroarchCore::ThreeDengine => "3dengine_libretro.dll",
                    RetroarchCore::EightOne => "81_libretro.dll",
                    RetroarchCore::TwoZeroFourEight => "2048_libretro.dll",
                    RetroarchCore::A5200 => "a5200_libretro.dll",
                    RetroarchCore::Anarch => "anarch_libretro.dll",
                    RetroarchCore::Ardens => "ardens_libretro.dll",
                    RetroarchCore::Arduous => "arduous_libretro.dll",
                    RetroarchCore::Atari800 => "atari800_libretro.dll",
                    RetroarchCore::B2 => "b2_libretro.dll",
                    RetroarchCore::Bk => "bk_libretro.dll",
                    RetroarchCore::Blastem => "blastem_libretro.dll",
                    RetroarchCore::Bluemsx => "bluemsx_libretro.dll",
                    RetroarchCore::Boom3 => "boom3_libretro.dll",
                    RetroarchCore::Boom3Xp => "boom3_xp_libretro.dll",
                    RetroarchCore::BsnesHdBeta => "bsnes_hd_beta_libretro.dll",
                    RetroarchCore::Bsnes => "bsnes_libretro.dll",
                    RetroarchCore::Cannonball => "cannonball_libretro.dll",
                    RetroarchCore::Cap32 => "cap32_libretro.dll",
                    RetroarchCore::Cdi2015 => "cdi2015_libretro.dll",
                    RetroarchCore::Chailove => "chailove_libretro.dll",
                    RetroarchCore::Citra => "citra_libretro.dll",
                    RetroarchCore::Clownmdemu => "clownmdemu_libretro.dll",
                    RetroarchCore::Craft => "craft_libretro.dll",
                    RetroarchCore::Crocods => "crocods_libretro.dll",
                    RetroarchCore::Desmume2015 => "desmume2015_libretro.dll",
                    RetroarchCore::Desmume => "desmume_libretro.dll",
                    RetroarchCore::Dice => "dice_libretro.dll",
                    RetroarchCore::Dinothawr => "dinothawr_libretro.dll",
                    RetroarchCore::Dirksimple => "dirksimple_libretro.dll",
                    RetroarchCore::Dolphin => "dolphin_libretro.dll",
                    RetroarchCore::DosboxCore => "dosbox_core_libretro.dll",
                    RetroarchCore::DosboxPure => "dosbox_pure_libretro.dll",
                    RetroarchCore::DosboxSvn => "dosbox_svn_libretro.dll",
                    RetroarchCore::Doublecherrygb => "DoubleCherryGB_libretro.dll",
                    RetroarchCore::DoukutsuRs => "doukutsu_rs_libretro.dll",
                    RetroarchCore::Easyrpg => "easyrpg_libretro.dll",
                    RetroarchCore::Ecwolf => "ecwolf_libretro.dll",
                    RetroarchCore::Ep128emuCore => "ep128emu_core_libretro.dll",
                    RetroarchCore::Fbalpha2012Cps1 => "fbalpha2012_cps1_libretro.dll",
                    RetroarchCore::Fbalpha2012Cps2 => "fbalpha2012_cps2_libretro.dll",
                    RetroarchCore::Fbalpha2012Cps3 => "fbalpha2012_cps3_libretro.dll",
                    RetroarchCore::Fbalpha2012 => "fbalpha2012_libretro.dll",
                    RetroarchCore::Fbalpha2012Neogeo => "fbalpha2012_neogeo_libretro.dll",
                    RetroarchCore::Fbalpha => "fbalpha_libretro.dll",
                    RetroarchCore::Fbneo => "fbneo_libretro.dll",
                    RetroarchCore::Fceumm => "fceumm_libretro.dll",
                    RetroarchCore::Fixgb => "fixgb_libretro.dll",
                    RetroarchCore::Fixnes => "fixnes_libretro.dll",
                    RetroarchCore::Flycast => "flycast_libretro.dll",
                    RetroarchCore::Fmsx => "fmsx_libretro.dll",
                    RetroarchCore::Freechaf => "freechaf_libretro.dll",
                    RetroarchCore::Freeintv => "freeintv_libretro.dll",
                    RetroarchCore::Frodo => "frodo_libretro.dll",
                    RetroarchCore::Fuse => "fuse_libretro.dll",
                    RetroarchCore::Galaksija => "galaksija_libretro.dll",
                    RetroarchCore::Gam4980 => "gam4980_libretro.dll",
                    RetroarchCore::Gambatte => "gambatte_libretro.dll",
                    RetroarchCore::Gearboy => "gearboy_libretro.dll",
                    RetroarchCore::Gearcoleco => "gearcoleco_libretro.dll",
                    RetroarchCore::Geargrafx => "geargrafx_libretro.dll",
                    RetroarchCore::Gearsystem => "gearsystem_libretro.dll",
                    RetroarchCore::GenesisPlusGx => "genesis_plus_gx_libretro.dll",
                    RetroarchCore::GenesisPlusGxWide => "genesis_plus_gx_wide_libretro.dll",
                    RetroarchCore::Geolith => "geolith_libretro.dll",
                    RetroarchCore::Gme => "gme_libretro.dll",
                    RetroarchCore::Gong => "gong_libretro.dll",
                    RetroarchCore::Gw => "gw_libretro.dll",
                    RetroarchCore::Handy => "handy_libretro.dll",
                    RetroarchCore::Hatari => "hatari_libretro.dll",
                    RetroarchCore::Holani => "holani_libretro.dll",
                    RetroarchCore::Jaxe => "jaxe_libretro.dll",
                    RetroarchCore::Jumpnbump => "jumpnbump_libretro.dll",
                    RetroarchCore::Kronos => "kronos_libretro.dll",
                    RetroarchCore::Lowresnx => "lowresnx_libretro.dll",
                    RetroarchCore::Lutro => "lutro_libretro.dll",
                    RetroarchCore::M2000 => "m2000_libretro.dll",
                    RetroarchCore::Mame2000 => "mame2000_libretro.dll",
                    RetroarchCore::Mame2003 => "mame2003_libretro.dll",
                    RetroarchCore::Mame2003Midway => "mame2003_midway_libretro.dll",
                    RetroarchCore::Mame2003Plus => "mame2003_plus_libretro.dll",
                    RetroarchCore::Mame2010 => "mame2010_libretro.dll",
                    RetroarchCore::Mame => "mame_libretro.dll",
                    RetroarchCore::Mcsoftserve => "mcsoftserve_libretro.dll",
                    RetroarchCore::MednafenGba => "mednafen_gba_libretro.dll",
                    RetroarchCore::MednafenLynx => "mednafen_lynx_libretro.dll",
                    RetroarchCore::MednafenNgp => "mednafen_ngp_libretro.dll",
                    RetroarchCore::MednafenPceFast => "mednafen_pce_fast_libretro.dll",
                    RetroarchCore::MednafenPce => "mednafen_pce_libretro.dll",
                    RetroarchCore::MednafenPcfx => "mednafen_pcfx_libretro.dll",
                    RetroarchCore::MednafenPsxHw => "mednafen_psx_hw_libretro.dll",
                    RetroarchCore::MednafenSaturn => "mednafen_saturn_libretro.dll",
                    RetroarchCore::MednafenSupafaust => "mednafen_supafaust_libretro.dll",
                    RetroarchCore::MednafenSupergrafx => "mednafen_supergrafx_libretro.dll",
                    RetroarchCore::MednafenVb => "mednafen_vb_libretro.dll",
                    RetroarchCore::MednafenWswan => "mednafen_wswan_libretro.dll",
                    RetroarchCore::Melonds => "melonds_libretro.dll",
                    RetroarchCore::Melondsds => "melondsds_libretro.dll",
                    RetroarchCore::MesenS => "mesen-s_libretro.dll",
                    RetroarchCore::Mesen => "mesen_libretro.dll",
                    RetroarchCore::Meteor => "meteor_libretro.dll",
                    RetroarchCore::Mgba => "mgba_libretro.dll",
                    RetroarchCore::Minivmac => "minivmac_libretro.dll",
                    RetroarchCore::Mojozork => "mojozork_libretro.dll",
                    RetroarchCore::MrBoom => "mr_boom_libretro.dll",
                    RetroarchCore::Mu => "mu_libretro.dll",
                    RetroarchCore::Mupen64plusNext => "mupen64plus_next_libretro.dll",
                    RetroarchCore::Nekop2 => "nekop2_libretro.dll",
                    RetroarchCore::Neocd => "neocd_libretro.dll",
                    RetroarchCore::Nestopia => "nestopia_libretro.dll",
                    RetroarchCore::Np2kai => "np2kai_libretro.dll",
                    RetroarchCore::Numero => "numero_libretro.dll",
                    RetroarchCore::Nxengine => "nxengine_libretro.dll",
                    RetroarchCore::O2em => "o2em_libretro.dll",
                    RetroarchCore::Oberon => "oberon_libretro.dll",
                    RetroarchCore::Openlara => "openlara_libretro.dll",
                    RetroarchCore::Opera => "opera_libretro.dll",
                    RetroarchCore::Panda3ds => "panda3ds_libretro.dll",
                    RetroarchCore::ParallelN64 => "parallel_n64_libretro.dll",
                    RetroarchCore::Pcsx2 => "pcsx2_libretro.dll",
                    RetroarchCore::PcsxRearmed => "pcsx_rearmed_libretro.dll",
                    RetroarchCore::Picodrive => "picodrive_libretro.dll",
                    RetroarchCore::Play => "play_libretro.dll",
                    RetroarchCore::Pocketcdg => "pocketcdg_libretro.dll",
                    RetroarchCore::Pokemini => "pokemini_libretro.dll",
                    RetroarchCore::Potator => "potator_libretro.dll",
                    RetroarchCore::Ppsspp => "ppsspp_libretro.dll",
                    RetroarchCore::PrBoom => "prboom_libretro.dll",
                    RetroarchCore::Prosystem => "prosystem_libretro.dll",
                    RetroarchCore::Puae2021 => "puae2021_libretro.dll",
                    RetroarchCore::Puae => "puae_libretro.dll",
                    RetroarchCore::Px68k => "px68k_libretro.dll",
                    RetroarchCore::Qemu => "qemu_libretro.dll",
                    RetroarchCore::Quasi88 => "quasi88_libretro.dll",
                    RetroarchCore::Quicknes => "quicknes_libretro.dll",
                    RetroarchCore::Race => "race_libretro.dll",
                    RetroarchCore::Reminiscence => "reminiscence_libretro.dll",
                    RetroarchCore::Retro8 => "retro8_libretro.dll",
                    RetroarchCore::Romcleaner => "romcleaner_libretro.dll",
                    RetroarchCore::SameCdi => "same_cdi_libretro.dll",
                    RetroarchCore::Sameboy => "sameboy_libretro.dll",
                    RetroarchCore::Sameduck => "sameduck_libretro.dll",
                    RetroarchCore::Scummvm => "scummvm_libretro.dll",
                    RetroarchCore::Smsplus => "smsplus_libretro.dll",
                    RetroarchCore::Snes9x => "snes9x_libretro.dll",
                    RetroarchCore::Squirreljme => "squirreljme_libretro.dll",
                    RetroarchCore::Stella2014 => "stella2014_libretro.dll",
                    RetroarchCore::Stella2023 => "stella2023_libretro.dll",
                    RetroarchCore::Stella => "stella_libretro.dll",
                    RetroarchCore::Superbroswar => "superbroswar_libretro.dll",
                    RetroarchCore::Swanstation => "swanstation_libretro.dll",
                    RetroarchCore::Tamalibretro => "tamalibretro_libretro.dll",
                    RetroarchCore::Tgbdual => "tgbdual_libretro.dll",
                    RetroarchCore::Theodore => "theodore_libretro.dll",
                    RetroarchCore::Thepowdertoy => "thepowdertoy_libretro.dll",
                    RetroarchCore::Tic80 => "tic80_libretro.dll",
                    RetroarchCore::Tyrquake => "tyrquake_libretro.dll",
                    RetroarchCore::Uw8 => "uw8_libretro.dll",
                    RetroarchCore::Uzem => "uzem_libretro.dll",
                    RetroarchCore::Vaporspec => "vaporspec_libretro.dll",
                    RetroarchCore::VbaNext => "vba_next_libretro.dll",
                    RetroarchCore::Vbam => "vbam_libretro.dll",
                    RetroarchCore::Vecx => "vecx_libretro.dll",
                    RetroarchCore::Vemulator => "vemulator_libretro.dll",
                    RetroarchCore::ViceX64 => "vice_x64_libretro.dll",
                    RetroarchCore::ViceX64sc => "vice_x64sc_libretro.dll",
                    RetroarchCore::ViceX128 => "vice_x128_libretro.dll",
                    RetroarchCore::ViceXcbm2 => "vice_xcbm2_libretro.dll",
                    RetroarchCore::ViceXcbm5x0 => "vice_xcbm5x0_libretro.dll",
                    RetroarchCore::ViceXpet => "vice_xpet_libretro.dll",
                    RetroarchCore::ViceXplus4 => "vice_xplus4_libretro.dll",
                    RetroarchCore::ViceXscpu64 => "vice_xscpu64_libretro.dll",
                    RetroarchCore::ViceXvic => "vice_xvic_libretro.dll",
                    RetroarchCore::Vircon32 => "vircon32_libretro.dll",
                    RetroarchCore::Virtualjaguar => "virtualjaguar_libretro.dll",
                    RetroarchCore::Virtualxt => "virtualxt_libretro.dll",
                    RetroarchCore::Vitaquake2Rogue => "vitaquake2-rogue_libretro.dll",
                    RetroarchCore::Vitaquake2Xatrix => "vitaquake2-xatrix_libretro.dll",
                    RetroarchCore::Vitaquake2Zaero => "vitaquake2-zaero_libretro.dll",
                    RetroarchCore::Vitaquake2 => "vitaquake2_libretro.dll",
                    RetroarchCore::Vitaquake3 => "vitaquake3_libretro.dll",
                    RetroarchCore::Wasm4 => "wasm4_libretro.dll",
                    RetroarchCore::X1 => "x1_libretro.dll",
                    RetroarchCore::Xrick => "xrick_libretro.dll",
                    RetroarchCore::Yabasanshiro => "yabasanshiro_libretro.dll",
                    RetroarchCore::Yabause => "yabause_libretro.dll",
                },
            },
            RetroarchRunner::NativeMacOs => RetroarchPlayerConfig {
                config_path: "$HOME/Library/Application Support/RetroArch/config",
                cores_path: "../cores",
                state_path: "../states",
                save_path: "../saves",
                rom_path,
                core_filename: match core {
                    RetroarchCore::ThreeDengine => "3dengine_libretro.dylib",
                    RetroarchCore::EightOne => "81_libretro.dylib",
                    RetroarchCore::TwoZeroFourEight => "2048_libretro.dylib",
                    RetroarchCore::A5200 => "a5200_libretro.dylib",
                    RetroarchCore::Anarch => "anarch_libretro.dylib",
                    RetroarchCore::Ardens => "ardens_libretro.dylib",
                    RetroarchCore::Arduous => "arduous_libretro.dylib",
                    RetroarchCore::Atari800 => "atari800_libretro.dylib",
                    RetroarchCore::B2 => "b2_libretro.dylib",
                    RetroarchCore::Bk => "bk_libretro.dylib",
                    RetroarchCore::Blastem => "blastem_libretro.dylib",
                    RetroarchCore::Bluemsx => "bluemsx_libretro.dylib",
                    RetroarchCore::Boom3 => "boom3_libretro.dylib",
                    RetroarchCore::Boom3Xp => "boom3_xp_libretro.dylib",
                    RetroarchCore::BsnesHdBeta => "bsnes_hd_beta_libretro.dylib",
                    RetroarchCore::Bsnes => "bsnes_libretro.dylib",
                    RetroarchCore::Cannonball => "cannonball_libretro.dylib",
                    RetroarchCore::Cap32 => "cap32_libretro.dylib",
                    RetroarchCore::Cdi2015 => "cdi2015_libretro.dylib",
                    RetroarchCore::Chailove => "chailove_libretro.dylib",
                    RetroarchCore::Citra => "citra_libretro.dylib",
                    RetroarchCore::Clownmdemu => "clownmdemu_libretro.dylib",
                    RetroarchCore::Craft => "craft_libretro.dylib",
                    RetroarchCore::Crocods => "crocods_libretro.dylib",
                    RetroarchCore::Desmume2015 => "desmume2015_libretro.dylib",
                    RetroarchCore::Desmume => "desmume_libretro.dylib",
                    RetroarchCore::Dice => "dice_libretro.dylib",
                    RetroarchCore::Dinothawr => "dinothawr_libretro.dylib",
                    RetroarchCore::Dirksimple => "dirksimple_libretro.dylib",
                    RetroarchCore::Dolphin => "dolphin_libretro.dylib",
                    RetroarchCore::DosboxCore => "dosbox_core_libretro.dylib",
                    RetroarchCore::DosboxPure => "dosbox_pure_libretro.dylib",
                    RetroarchCore::DosboxSvn => "dosbox_svn_libretro.dylib",
                    RetroarchCore::Doublecherrygb => "DoubleCherryGB_libretro.dylib",
                    RetroarchCore::DoukutsuRs => "doukutsu_rs_libretro.dylib",
                    RetroarchCore::Easyrpg => "easyrpg_libretro.dylib",
                    RetroarchCore::Ecwolf => "ecwolf_libretro.dylib",
                    RetroarchCore::Ep128emuCore => "ep128emu_core_libretro.dylib",
                    RetroarchCore::Fbalpha2012Cps1 => "fbalpha2012_cps1_libretro.dylib",
                    RetroarchCore::Fbalpha2012Cps2 => "fbalpha2012_cps2_libretro.dylib",
                    RetroarchCore::Fbalpha2012Cps3 => "fbalpha2012_cps3_libretro.dylib",
                    RetroarchCore::Fbalpha2012 => "fbalpha2012_libretro.dylib",
                    RetroarchCore::Fbalpha2012Neogeo => "fbalpha2012_neogeo_libretro.dylib",
                    RetroarchCore::Fbalpha => "fbalpha_libretro.dylib",
                    RetroarchCore::Fbneo => "fbneo_libretro.dylib",
                    RetroarchCore::Fceumm => "fceumm_libretro.dylib",
                    RetroarchCore::Fixgb => "fixgb_libretro.dylib",
                    RetroarchCore::Fixnes => "fixnes_libretro.dylib",
                    RetroarchCore::Flycast => "flycast_libretro.dylib",
                    RetroarchCore::Fmsx => "fmsx_libretro.dylib",
                    RetroarchCore::Freechaf => "freechaf_libretro.dylib",
                    RetroarchCore::Freeintv => "freeintv_libretro.dylib",
                    RetroarchCore::Frodo => "frodo_libretro.dylib",
                    RetroarchCore::Fuse => "fuse_libretro.dylib",
                    RetroarchCore::Galaksija => "galaksija_libretro.dylib",
                    RetroarchCore::Gam4980 => "gam4980_libretro.dylib",
                    RetroarchCore::Gambatte => "gambatte_libretro.dylib",
                    RetroarchCore::Gearboy => "gearboy_libretro.dylib",
                    RetroarchCore::Gearcoleco => "gearcoleco_libretro.dylib",
                    RetroarchCore::Geargrafx => "geargrafx_libretro.dylib",
                    RetroarchCore::Gearsystem => "gearsystem_libretro.dylib",
                    RetroarchCore::GenesisPlusGx => "genesis_plus_gx_libretro.dylib",
                    RetroarchCore::GenesisPlusGxWide => "genesis_plus_gx_wide_libretro.dylib",
                    RetroarchCore::Geolith => "geolith_libretro.dylib",
                    RetroarchCore::Gme => "gme_libretro.dylib",
                    RetroarchCore::Gong => "gong_libretro.dylib",
                    RetroarchCore::Gw => "gw_libretro.dylib",
                    RetroarchCore::Handy => "handy_libretro.dylib",
                    RetroarchCore::Hatari => "hatari_libretro.dylib",
                    RetroarchCore::Holani => "holani_libretro.dylib",
                    RetroarchCore::Jaxe => "jaxe_libretro.dylib",
                    RetroarchCore::Jumpnbump => "jumpnbump_libretro.dylib",
                    RetroarchCore::Kronos => "kronos_libretro.dylib",
                    RetroarchCore::Lowresnx => "lowresnx_libretro.dylib",
                    RetroarchCore::Lutro => "lutro_libretro.dylib",
                    RetroarchCore::M2000 => "m2000_libretro.dylib",
                    RetroarchCore::Mame2000 => "mame2000_libretro.dylib",
                    RetroarchCore::Mame2003 => "mame2003_libretro.dylib",
                    RetroarchCore::Mame2003Midway => "mame2003_midway_libretro.dylib",
                    RetroarchCore::Mame2003Plus => "mame2003_plus_libretro.dylib",
                    RetroarchCore::Mame2010 => "mame2010_libretro.dylib",
                    RetroarchCore::Mame => "mame_libretro.dylib",
                    RetroarchCore::Mcsoftserve => "mcsoftserve_libretro.dylib",
                    RetroarchCore::MednafenGba => "mednafen_gba_libretro.dylib",
                    RetroarchCore::MednafenLynx => "mednafen_lynx_libretro.dylib",
                    RetroarchCore::MednafenNgp => "mednafen_ngp_libretro.dylib",
                    RetroarchCore::MednafenPceFast => "mednafen_pce_fast_libretro.dylib",
                    RetroarchCore::MednafenPce => "mednafen_pce_libretro.dylib",
                    RetroarchCore::MednafenPcfx => "mednafen_pcfx_libretro.dylib",
                    RetroarchCore::MednafenPsxHw => "mednafen_psx_hw_libretro.dylib",
                    RetroarchCore::MednafenSaturn => "mednafen_saturn_libretro.dylib",
                    RetroarchCore::MednafenSupafaust => "mednafen_supafaust_libretro.dylib",
                    RetroarchCore::MednafenSupergrafx => "mednafen_supergrafx_libretro.dylib",
                    RetroarchCore::MednafenVb => "mednafen_vb_libretro.dylib",
                    RetroarchCore::MednafenWswan => "mednafen_wswan_libretro.dylib",
                    RetroarchCore::Melonds => "melonds_libretro.dylib",
                    RetroarchCore::Melondsds => "melondsds_libretro.dylib",
                    RetroarchCore::MesenS => "mesen-s_libretro.dylib",
                    RetroarchCore::Mesen => "mesen_libretro.dylib",
                    RetroarchCore::Meteor => "meteor_libretro.dylib",
                    RetroarchCore::Mgba => "mgba_libretro.dylib",
                    RetroarchCore::Minivmac => "minivmac_libretro.dylib",
                    RetroarchCore::Mojozork => "mojozork_libretro.dylib",
                    RetroarchCore::MrBoom => "mr_boom_libretro.dylib",
                    RetroarchCore::Mu => "mu_libretro.dylib",
                    RetroarchCore::Mupen64plusNext => "mupen64plus_next_libretro.dylib",
                    RetroarchCore::Nekop2 => "nekop2_libretro.dylib",
                    RetroarchCore::Neocd => "neocd_libretro.dylib",
                    RetroarchCore::Nestopia => "nestopia_libretro.dylib",
                    RetroarchCore::Np2kai => "np2kai_libretro.dylib",
                    RetroarchCore::Numero => "numero_libretro.dylib",
                    RetroarchCore::Nxengine => "nxengine_libretro.dylib",
                    RetroarchCore::O2em => "o2em_libretro.dylib",
                    RetroarchCore::Oberon => "oberon_libretro.dylib",
                    RetroarchCore::Openlara => "openlara_libretro.dylib",
                    RetroarchCore::Opera => "opera_libretro.dylib",
                    RetroarchCore::Panda3ds => "panda3ds_libretro.dylib",
                    RetroarchCore::ParallelN64 => "parallel_n64_libretro.dylib",
                    RetroarchCore::Pcsx2 => "pcsx2_libretro.dylib",
                    RetroarchCore::PcsxRearmed => "pcsx_rearmed_libretro.dylib",
                    RetroarchCore::Picodrive => "picodrive_libretro.dylib",
                    RetroarchCore::Play => "play_libretro.dylib",
                    RetroarchCore::Pocketcdg => "pocketcdg_libretro.dylib",
                    RetroarchCore::Pokemini => "pokemini_libretro.dylib",
                    RetroarchCore::Potator => "potator_libretro.dylib",
                    RetroarchCore::Ppsspp => "ppsspp_libretro.dylib",
                    RetroarchCore::PrBoom => "prboom_libretro.dylib",
                    RetroarchCore::Prosystem => "prosystem_libretro.dylib",
                    RetroarchCore::Puae2021 => "puae2021_libretro.dylib",
                    RetroarchCore::Puae => "puae_libretro.dylib",
                    RetroarchCore::Px68k => "px68k_libretro.dylib",
                    RetroarchCore::Qemu => "qemu_libretro.dylib",
                    RetroarchCore::Quasi88 => "quasi88_libretro.dylib",
                    RetroarchCore::Quicknes => "quicknes_libretro.dylib",
                    RetroarchCore::Race => "race_libretro.dylib",
                    RetroarchCore::Reminiscence => "reminiscence_libretro.dylib",
                    RetroarchCore::Retro8 => "retro8_libretro.dylib",
                    RetroarchCore::Romcleaner => "romcleaner_libretro.dylib",
                    RetroarchCore::SameCdi => "same_cdi_libretro.dylib",
                    RetroarchCore::Sameboy => "sameboy_libretro.dylib",
                    RetroarchCore::Sameduck => "sameduck_libretro.dylib",
                    RetroarchCore::Scummvm => "scummvm_libretro.dylib",
                    RetroarchCore::Smsplus => "smsplus_libretro.dylib",
                    RetroarchCore::Snes9x => "snes9x_libretro.dylib",
                    RetroarchCore::Squirreljme => "squirreljme_libretro.dylib",
                    RetroarchCore::Stella2014 => "stella2014_libretro.dylib",
                    RetroarchCore::Stella2023 => "stella2023_libretro.dylib",
                    RetroarchCore::Stella => "stella_libretro.dylib",
                    RetroarchCore::Superbroswar => "superbroswar_libretro.dylib",
                    RetroarchCore::Swanstation => "swanstation_libretro.dylib",
                    RetroarchCore::Tamalibretro => "tamalibretro_libretro.dylib",
                    RetroarchCore::Tgbdual => "tgbdual_libretro.dylib",
                    RetroarchCore::Theodore => "theodore_libretro.dylib",
                    RetroarchCore::Thepowdertoy => "thepowdertoy_libretro.dylib",
                    RetroarchCore::Tic80 => "tic80_libretro.dylib",
                    RetroarchCore::Tyrquake => "tyrquake_libretro.dylib",
                    RetroarchCore::Uw8 => "uw8_libretro.dylib",
                    RetroarchCore::Uzem => "uzem_libretro.dylib",
                    RetroarchCore::Vaporspec => "vaporspec_libretro.dylib",
                    RetroarchCore::VbaNext => "vba_next_libretro.dylib",
                    RetroarchCore::Vbam => "vbam_libretro.dylib",
                    RetroarchCore::Vecx => "vecx_libretro.dylib",
                    RetroarchCore::Vemulator => "vemulator_libretro.dylib",
                    RetroarchCore::ViceX64 => "vice_x64_libretro.dylib",
                    RetroarchCore::ViceX64sc => "vice_x64sc_libretro.dylib",
                    RetroarchCore::ViceX128 => "vice_x128_libretro.dylib",
                    RetroarchCore::ViceXcbm2 => "vice_xcbm2_libretro.dylib",
                    RetroarchCore::ViceXcbm5x0 => "vice_xcbm5x0_libretro.dylib",
                    RetroarchCore::ViceXpet => "vice_xpet_libretro.dylib",
                    RetroarchCore::ViceXplus4 => "vice_xplus4_libretro.dylib",
                    RetroarchCore::ViceXscpu64 => "vice_xscpu64_libretro.dylib",
                    RetroarchCore::ViceXvic => "vice_xvic_libretro.dylib",
                    RetroarchCore::Vircon32 => "vircon32_libretro.dylib",
                    RetroarchCore::Virtualjaguar => "virtualjaguar_libretro.dylib",
                    RetroarchCore::Virtualxt => "virtualxt_libretro.dylib",
                    RetroarchCore::Vitaquake2Rogue => "vitaquake2-rogue_libretro.dylib",
                    RetroarchCore::Vitaquake2Xatrix => "vitaquake2-xatrix_libretro.dylib",
                    RetroarchCore::Vitaquake2Zaero => "vitaquake2-zaero_libretro.dylib",
                    RetroarchCore::Vitaquake2 => "vitaquake2_libretro.dylib",
                    RetroarchCore::Vitaquake3 => "vitaquake3_libretro.dylib",
                    RetroarchCore::Wasm4 => "wasm4_libretro.dylib",
                    RetroarchCore::X1 => "x1_libretro.dylib",
                    RetroarchCore::Xrick => "xrick_libretro.dylib",
                    RetroarchCore::Yabasanshiro => "yabasanshiro_libretro.dylib",
                    RetroarchCore::Yabause => "yabause_libretro.dylib",
                },
            },
        }
    }

    pub async fn play(&self, app_handle: &AppHandle) -> Result<String, Error> {
        let download_dir = Downloader::get_download_path()?;
        let shell = app_handle.shell();
        let command = shell.command("flatpak").args([
            "run",
            "org.libretro.RetroArch",
            "--fullscreen",
            "-L",
            self.core_filename,
            format!("{download_dir}{}", self.rom_path).as_str(),
        ]);

        let output = match command.output().await {
            Ok(output) => Ok(output),
            Err(e) => Err(Error::InternalServer(e.to_string())),
        }?;

        println!(
            "{:?} - {:?}",
            String::from_utf8(output.stdout),
            String::from_utf8(output.stderr)
        );

        Ok("".to_string())
    }
}
