enum QueryKey {
	ROMS = 'ROMS',
	ROM_BY_ID = 'ROM_BY_ID',
	RECENTLY_PLAYED = 'RECENTLY_PLAYED',
	RECENTLY_ADDED = 'RECENTLY_ADDED',
	CURRENT_USER = 'CURRENT_USER',
	PLATFORMS = 'PLATFORMS'
}

export default QueryKey
