enum QueryKey {
	ROMS = 'ROMS',
	ROM_BY_ID = 'ROM_BY_ID',
	ROM_BY_COLLECTION_ID = 'ROM_BY_COLLECTION_ID',
	ROM_BY_PLATFORM_ID = 'ROM_BY_PLATFORM_ID',
	RECENTLY_PLAYED = 'RECENTLY_PLAYED',
	RECENTLY_ADDED = 'RECENTLY_ADDED',
	CURRENT_USER = 'CURRENT_USER',
	PLATFORMS = 'PLATFORMS',
	COLLECTIONS = 'COLLECTIONS',
	ASSET = 'ASSET'
}

export default QueryKey
