enum QueryKey {
	ROMS = 'ROMS',
	ROM_BY_ID = 'ROM_BY_ID',
	ROM_BY_COLLECTION_ID = 'ROM_BY_COLLECTION_ID',
	ROM_BY_COLLECTION_ID_PAGINATED = 'ROM_BY_COLLECTION_ID_PAGINATED',
	ROM_BY_PLATFORM_ID = 'ROM_BY_PLATFORM_ID',
	ROM_BY_PLATFORM_ID_PAGINATED = 'ROM_BY_PLATFORM_ID_PAGINATED',
	RECENTLY_PLAYED = 'RECENTLY_PLAYED',
	RECENTLY_ADDED = 'RECENTLY_ADDED',
	CURRENT_USER = 'CURRENT_USER',
	PLATFORMS = 'PLATFORMS',
	COLLECTIONS = 'COLLECTIONS',
	ASSET = 'ASSET',
	CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD',
	IS_FILE_DOWNLOADED = 'IS_FILE_DOWNLOADED'
}

export default QueryKey
