export enum RetroarchCore {
	BSNES_HD_BETA = 'bsneshdbeta',
	BSNES = 'bsnes',
	CITRA = 'citra',
	DOLPHIN = 'dolphin',
	GENESIS_PLUS_GX = 'genesisplusgx',
	GENESIS_PLUS_GX_WIDE = 'genesisplusgxwide',
	PCSX = 'pcsx',
	MELONDS = 'melonds',
	MELONDSDS = 'melondsds',
	MGBA = 'mgba',
	MUPEN64PLUS_NEXT = 'mupen64plusnext',
	PARALLEL_N64 = 'paralleln64',
	PPSSPP = 'ppsspp',
	SNES9X = 'snes9x',
	VITAQUAKE2_ROGUE = 'vitaquake2rogue',
	VITAQUAKE2_XATRIX = 'vitaquake2xatrix',
	VITAQUAKE2_ZAERO = 'vitaquake2zaero',
	VITAQUAKE2 = 'vitaquake2',
	VITAQUAKE3 = 'vitaquake3'
}
