export enum RetroarchCore {
	BSNES_HD_BETA = 'bsnes_hd_beta',
	BSNES = 'bsnes',
	CITRA = 'citra',
	DOLPHIN = 'dolphin',
	GENESIS_PLUS_GX = 'genesis_plus_gx',
	GENESIS_PLUS_GX_WIDE = 'genesis_plus_gx_wide',
	MEDNAFEN_PSX_HW = 'mednafen_psx_hw',
	MELONDS = 'melonds',
	MELONDSDS = 'melondsds',
	MGBA = 'mgba',
	MUPEN64PLUS_NEXT = 'mupen64plus_next',
	PPSSPP = 'ppsspp',
	SNES9X = 'snes9x',
	VITAQUAKE2_ROGUE = 'vitaquake2_rogue',
	VITAQUAKE2_XATRIX = 'vitaquake2_xatrix',
	VITAQUAKE2_ZAERO = 'vitaquake2_zaero',
	VITAQUAKE2 = 'vitaquake2',
	VITAQUAKE3 = 'vitaquake3'
}
